/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as GuardianRouteImport } from './routes/guardian'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuardianIndexRouteImport } from './routes/guardian.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as GuardianMapRouteImport } from './routes/guardian.map'
import { Route as GuardianAlertsRouteImport } from './routes/guardian.alerts'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AppZonesRouteImport } from './routes/app.zones'
import { Route as AppSosRouteImport } from './routes/app.sos'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppMapRouteImport } from './routes/app.map'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppDeviceRouteImport } from './routes/app.device'
import { Route as AppContactsRouteImport } from './routes/app.contacts'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as GuardianZonesUserIdRouteImport } from './routes/guardian.zones.$userId'
import { Route as GuardianWearerUserIdRouteImport } from './routes/guardian.wearer.$userId'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianRoute = GuardianRouteImport.update({
  id: '/guardian',
  path: '/guardian',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianIndexRoute = GuardianIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuardianRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const GuardianMapRoute = GuardianMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => GuardianRoute,
} as any)
const GuardianAlertsRoute = GuardianAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => GuardianRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppZonesRoute = AppZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => AppRoute,
} as any)
const AppSosRoute = AppSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppDeviceRoute = AppDeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianZonesUserIdRoute = GuardianZonesUserIdRouteImport.update({
  id: '/zones/$userId',
  path: '/zones/$userId',
  getParentRoute: () => GuardianRoute,
} as any)
const GuardianWearerUserIdRoute = GuardianWearerUserIdRouteImport.update({
  id: '/wearer/$userId',
  path: '/wearer/$userId',
  getParentRoute: () => GuardianRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/guardian': typeof GuardianRouteWithChildren
  '/unsubscribe': typeof UnsubscribeRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/device': typeof AppDeviceRoute
  '/app/history': typeof AppHistoryRoute
  '/app/map': typeof AppMapRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sos': typeof AppSosRoute
  '/app/zones': typeof AppZonesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/guardian/alerts': typeof GuardianAlertsRoute
  '/guardian/map': typeof GuardianMapRoute
  '/app/': typeof AppIndexRoute
  '/guardian/': typeof GuardianIndexRoute
  '/guardian/wearer/$userId': typeof GuardianWearerUserIdRoute
  '/guardian/zones/$userId': typeof GuardianZonesUserIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/unsubscribe': typeof UnsubscribeRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/device': typeof AppDeviceRoute
  '/app/history': typeof AppHistoryRoute
  '/app/map': typeof AppMapRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sos': typeof AppSosRoute
  '/app/zones': typeof AppZonesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/guardian/alerts': typeof GuardianAlertsRoute
  '/guardian/map': typeof GuardianMapRoute
  '/app': typeof AppIndexRoute
  '/guardian': typeof GuardianIndexRoute
  '/guardian/wearer/$userId': typeof GuardianWearerUserIdRoute
  '/guardian/zones/$userId': typeof GuardianZonesUserIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/guardian': typeof GuardianRouteWithChildren
  '/unsubscribe': typeof UnsubscribeRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/device': typeof AppDeviceRoute
  '/app/history': typeof AppHistoryRoute
  '/app/map': typeof AppMapRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sos': typeof AppSosRoute
  '/app/zones': typeof AppZonesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/guardian/alerts': typeof GuardianAlertsRoute
  '/guardian/map': typeof GuardianMapRoute
  '/app/': typeof AppIndexRoute
  '/guardian/': typeof GuardianIndexRoute
  '/guardian/wearer/$userId': typeof GuardianWearerUserIdRoute
  '/guardian/zones/$userId': typeof GuardianZonesUserIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/guardian'
    | '/unsubscribe'
    | '/app/contacts'
    | '/app/device'
    | '/app/history'
    | '/app/map'
    | '/app/settings'
    | '/app/sos'
    | '/app/zones'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/email/unsubscribe'
    | '/guardian/alerts'
    | '/guardian/map'
    | '/app/'
    | '/guardian/'
    | '/guardian/wearer/$userId'
    | '/guardian/zones/$userId'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/unsubscribe'
    | '/app/contacts'
    | '/app/device'
    | '/app/history'
    | '/app/map'
    | '/app/settings'
    | '/app/sos'
    | '/app/zones'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/email/unsubscribe'
    | '/guardian/alerts'
    | '/guardian/map'
    | '/app'
    | '/guardian'
    | '/guardian/wearer/$userId'
    | '/guardian/zones/$userId'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/guardian'
    | '/unsubscribe'
    | '/app/contacts'
    | '/app/device'
    | '/app/history'
    | '/app/map'
    | '/app/settings'
    | '/app/sos'
    | '/app/zones'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/email/unsubscribe'
    | '/guardian/alerts'
    | '/guardian/map'
    | '/app/'
    | '/guardian/'
    | '/guardian/wearer/$userId'
    | '/guardian/zones/$userId'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  GuardianRoute: typeof GuardianRouteWithChildren
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian': {
      id: '/guardian'
      path: '/guardian'
      fullPath: '/guardian'
      preLoaderRoute: typeof GuardianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/': {
      id: '/guardian/'
      path: '/'
      fullPath: '/guardian/'
      preLoaderRoute: typeof GuardianIndexRouteImport
      parentRoute: typeof GuardianRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/guardian/map': {
      id: '/guardian/map'
      path: '/map'
      fullPath: '/guardian/map'
      preLoaderRoute: typeof GuardianMapRouteImport
      parentRoute: typeof GuardianRoute
    }
    '/guardian/alerts': {
      id: '/guardian/alerts'
      path: '/alerts'
      fullPath: '/guardian/alerts'
      preLoaderRoute: typeof GuardianAlertsRouteImport
      parentRoute: typeof GuardianRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/zones': {
      id: '/app/zones'
      path: '/zones'
      fullPath: '/app/zones'
      preLoaderRoute: typeof AppZonesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sos': {
      id: '/app/sos'
      path: '/sos'
      fullPath: '/app/sos'
      preLoaderRoute: typeof AppSosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/map': {
      id: '/app/map'
      path: '/map'
      fullPath: '/app/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/device': {
      id: '/app/device'
      path: '/device'
      fullPath: '/app/device'
      preLoaderRoute: typeof AppDeviceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contacts': {
      id: '/app/contacts'
      path: '/contacts'
      fullPath: '/app/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/zones/$userId': {
      id: '/guardian/zones/$userId'
      path: '/zones/$userId'
      fullPath: '/guardian/zones/$userId'
      preLoaderRoute: typeof GuardianZonesUserIdRouteImport
      parentRoute: typeof GuardianRoute
    }
    '/guardian/wearer/$userId': {
      id: '/guardian/wearer/$userId'
      path: '/wearer/$userId'
      fullPath: '/guardian/wearer/$userId'
      preLoaderRoute: typeof GuardianWearerUserIdRouteImport
      parentRoute: typeof GuardianRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppContactsRoute: typeof AppContactsRoute
  AppDeviceRoute: typeof AppDeviceRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppMapRoute: typeof AppMapRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSosRoute: typeof AppSosRoute
  AppZonesRoute: typeof AppZonesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppContactsRoute: AppContactsRoute,
  AppDeviceRoute: AppDeviceRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppMapRoute: AppMapRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSosRoute: AppSosRoute,
  AppZonesRoute: AppZonesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface GuardianRouteChildren {
  GuardianAlertsRoute: typeof GuardianAlertsRoute
  GuardianMapRoute: typeof GuardianMapRoute
  GuardianIndexRoute: typeof GuardianIndexRoute
  GuardianWearerUserIdRoute: typeof GuardianWearerUserIdRoute
  GuardianZonesUserIdRoute: typeof GuardianZonesUserIdRoute
}

const GuardianRouteChildren: GuardianRouteChildren = {
  GuardianAlertsRoute: GuardianAlertsRoute,
  GuardianMapRoute: GuardianMapRoute,
  GuardianIndexRoute: GuardianIndexRoute,
  GuardianWearerUserIdRoute: GuardianWearerUserIdRoute,
  GuardianZonesUserIdRoute: GuardianZonesUserIdRoute,
}

const GuardianRouteWithChildren = GuardianRoute._addFileChildren(
  GuardianRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  GuardianRoute: GuardianRouteWithChildren,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
